version: 2

project_name: bgrun

before:
  hooks:
    - rustup default stable
    - cargo install --locked cargo-zigbuild

builds:
  - id: bgrun
    builder: rust
    binary: bgrun
    flags:
      - --release
      - -p=bgrun-cli
    targets:
      - x86_64-unknown-linux-gnu
      - aarch64-unknown-linux-gnu

  - id: bgrun-daemon
    builder: rust
    binary: bgrun-daemon
    flags:
      - --release
      - -p=bgrun-daemon
    targets:
      - x86_64-unknown-linux-gnu
      - aarch64-unknown-linux-gnu

archives:
  - id: bgrun
    ids:
      - bgrun
      - bgrun-daemon
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - docs/*

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
